@DOMAIN = https://localhost
@PORT = 8443
@API_URL = {{DOMAIN}}:{{PORT}}
@TOKEN =

###
# AUTH
###
GET {{API_URL}}/users

### OWNER REGISTRATION

POST {{API_URL}}/register
Content-Type: application/json

{
  "username": "ristoratore",
  "password": "password",
  "role": "OWNER"
}

### CUSTOMER REGISTRATION

POST {{API_URL}}/register
Content-Type: application/json

{
  "username": "cliente",
  "password": "password",
  "role": "CUSTOMER"
}

###

POST {{API_URL}}/login
Content-Type: application/json

{
  "username": "ristoratore",
  "password": "password"
}

###

GET {{API_URL}}/restaurants
Authorization: Bearer {{TOKEN}}

###

GET {{API_URL}}/restaurants/123
Authorization: Bearer {{TOKEN}}

###

POST {{API_URL}}/restaurants
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Pizza giustissima"
}

###

PUT {{API_URL}}/restaurants/123
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Pizza giustissima"
}