@DOMAIN = https://localhost
@PORT = 8443
@API_URL = {{DOMAIN}}:{{PORT}}

###
# AUTH
###
GET {{API_URL}}/users

###

POST {{API_URL}}/auth/register
Content-Type: application/json

{
  "username": "Kyle",
  "password": "password"
}

###

POST {{API_URL}}/auth/login
Content-Type: application/json

{
  "username": "Kyle",
  "password": "password"
}

###

GET {{API_URL}}/restaurants/123

###

GET {{API_URL}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGUiLCJpYXQiOjE2NjM2MjQ2NjEsImV4cCI6MTY2MzYyODI2MX0.LgSzTlU0pcH2dYl-xFZaTRhGB_JwL3rFpt8EVQi35BM