@DOMAIN = https://localhost
@PORT = 8443
@API_URL = {{DOMAIN}}:{{PORT}}
@TOKEN =

# TODO
GET {{API_URL}}/users

### REGISTRATION

POST {{API_URL}}/register
Content-Type: application/json

{
  "username": "ristoratore",
  "password": "password",
  "role": "OWNER"
}

###

POST {{API_URL}}/register
Content-Type: application/json

{
  "username": "cliente",
  "password": "password",
  "role": "CUSTOMER"
}

### LOGIN

POST {{API_URL}}/login
Content-Type: application/json

{
  "username": "ristoratore",
  "password": "password"
}

### RESTAURANTS

GET {{API_URL}}/restaurants
Authorization: Bearer {{TOKEN}}

###

GET {{API_URL}}/restaurants/123
Authorization: Bearer {{TOKEN}}

###

POST {{API_URL}}/restaurants
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Pizza giustissima"
}

###

PUT {{API_URL}}/restaurants/123
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "Pizza giustissima"
}

###

DELETE {{API_URL}}/restaurants/390
Authorization: Bearer {{TOKEN}}
